bundle:
    name: FavoriteBundle
    description: Allow users to put class contents in "Favorites"
    author: Mickaël Andrieu <mickael.andrieu@lp-digital.fr>
    version: 1
    enable: true
    config_per_site: false
    admin_controller:
        admin: LpDigital\Bundle\FavoriteBundle\Controller\AdminController
    admin_entry_point: admin.index